name: navocean-environment
channels:
  - conda-forge
dependencies:
  - numpy=1.20.2
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - pandas=1.2.3
  - cartopy=0.17.0
  - dask=2021.4.0
  - pillow=8.1.2
