name: navocean-environment
  -python=3.7
channels:
  - conda-forge
  - defaults
dependencies:
  - Cartopy=0.18.*
  - cython
  - numpy=1.20.*
  - matplotlib=3.4.*
  - matplotlib-base=3.4.*
  - pandas=1.2.*
  - pillow=8.1.*
